### ISSUE TITLE
Using tokenizer as unified understanding and generation

### ISSUE THREAD

**Issue by luohao123** [NVIDIA/Cosmos-Tokenizer#3]
From I can sees, 8x8 downsampling still produce a lot tokens. It's that possible make this workable on both understanding and generation.

**Comment by Haoxiang-Wang** [comment]
Yes, you could use the tokenizer for both understanding and generation. 

References:
1. Chameleon: https://ai.meta.com/blog/generative-ai-text-images-cm3leon/
2. Emu3: https://emu.baai.ac.cn/

**Comment by luohao123** [comment]
Hi, how does the long tokens num issue could resolved? For instance, 512 x8 would have 4k tokens, isn't it? @Haoxiang-Wang
